disabled_rules:
  - line_length
  - opening_brace
  - type_name
  - todo
  - syntactic_sugar
  - trailing_comma
  - redundant_string_enum_value
  - redundant_optional_initialization
  - large_tuple
  - force_cast
  - force_try
included:
  - Source
  - Specs
  - Features
excluded:
  - Carthage
opt_in_rules:
  - empty_count

